# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mindose',
                'doc_host': 'https://mindose.github.io',
                'git_url': 'https://github.com/mindose/mindose',
                'lib_path': 'mindose'},
  'syms': {'mindose.core': {'mindose.core.foo': ('core.html#foo', 'mindose/core.py')}}}
